### ISSUE TITLE
`manuale register ...` "unhandled error": stat: can't specify None for path argument

### ISSUE THREAD

**Issue by ghost** [veeti/manuale#11]
```
git clone https://github.com/veeti/manuale.git
cd manuale
git log | head
    commit 1de8f90bc8ec633b0c53cf0d1b923fe8b39c82e4
    Author: Veeti Paananen <veeti.paananen@rojekti.fi>
    Date:   Tue Feb 9 19:07:44 2016 +0200

        1.0.2.dev0

    commit c826e2483b5515a3e316bafa33fac248c6e91993
    Author: Veeti Paananen <veeti.paananen@rojekti.fi>
    Date:   Tue Feb 9 18:54:27 2016 +0200


python --version
    Python 3.4.1
python setup.py install
which manuale
    /usr/bin/manuale
manuale -h
    usage: manuale [-h] [--server SERVER] [--account ACCOUNT]
                   {register,authorize,issue,revoke,info,version} ...

    Interact with ACME certification authorities such as Let's Encrypt.

    No idea what you're doing? Register an account, authorize your domains and
    issue a certificate or two. Call a command with -h for more instructions.

    positional arguments:
      {register,authorize,issue,revoke,info,version}
        register            Create a new account and register
        authorize           Verify domain ownership
        issue               Request a new certificate
        revoke              Revoke an issued certificate
        info                Shows account information from the service
        version             Show the version number

    optional arguments:
      -h, --help            show this help message and exit
      --server SERVER, -s SERVER
                            The ACME server to use (default:
                            https://acme-v01.api.letsencrypt.org/)
      --account ACCOUNT, -a ACCOUNT
                            The account file to use or create (default:
                            account.json)

manuale register test@example.com
    You're about to register a new account with the e-mail test@example.com. Continue? [Y/n] Y
    Generating a new account key. This might take a second.
    Key generated.
    Registering...
    Oops! An unhandled error occurred. Please file a bug.
    stat: can't specify None for path argument
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/cli.py", line 229, in main
        args.func(args)
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/cli.py", line 97, in _register
        register(args.server, args.account, args.email)
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/register.py", line 35, in register
        registration = acme.register(email)
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/acme.py", line 48, in register
        "mailto:{}".format(email)
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/acme.py", line 165, in post
        header, protected = self.get_headers()
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/acme.py", line 38, in get_headers
        protected_header['nonce'] = self.get_nonce()
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/acme.py", line 30, in get_nonce
        return self.get('/directory').headers.get('Replay-Nonce')
      File "/usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg/manuale/acme.py", line 157, in get
        return requests.get(self.path(path), headers=_headers)
      File "/usr/lib/python3.4/site-packages/requests/api.py", line 67, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/lib/python3.4/site-packages/requests/api.py", line 53, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 342, in send
        self.cert_verify(conn, request.url, verify, cert)
      File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 187, in cert_verify
        if not os.path.isdir(cert_loc):
      File "/usr/lib64/python3.4/genericpath.py", line 42, in isdir
        st = os.stat(s)
    TypeError: stat: can't specify None for path argument
```

**Comment by veeti** [comment]
Error seems to be coming from the `requests` library. What operating system/distribution are you running? Could you try doing a clean install inside a virtualenv using pip instead, as detailed in the readme? This will pull the latest version of all dependencies from PyPI instead of using whatever your system already has installed.

**Comment by ghost** [comment]
> What operating system/distribution are you running?

```
lsb_release -d
    Description:    openSUSE Leap 42.1 (x86_64)
python -V
    Python 3.4.1
pip -V
    pip 8.0.2 from /usr/lib/python3.4/site-packages (python 3.4)
```

> Could you try doing a clean install inside a virtualenv using pip instead, as detailed in the readme

```
find /usr/lib*/python* | grep -i manuale
    /usr/lib/python3.4/site-packages/manuale-1.0.2.dev0-py3.4.egg
rm -f /usr/lib/python3.4/site-packages/manuale*
rm -f /usr/local/bin/manuale*

cd /usr/local/src/
rm -rf manuale

git clone https://github.com/veeti/manuale.git
cd manuale

python3 -m venv env
env/bin/python setup.py install
    ...
    Installing easy_install-3.4 script to /usr/local/src/manuale/env/bin
    Installing easy_install script to /usr/local/src/manuale/env/bin

    Using /usr/local/src/manuale/env/lib/python3.4/site-packages
    Finished processing dependencies for manuale==1.0.2.dev0

ls -al env/bin/python*
    lrwxrwxrwx 1 root root  7 Feb 21 12:55 env/bin/python -> python3*
    lrwxrwxrwx 1 root root 16 Feb 21 12:55 env/bin/python3 -> /usr/bin/python3*
ln -sf `pwd`/env/bin/manuale /usr/local/bin/
which manuale
    /usr/local/bin/manuale

manuale register test@example.com
    Traceback (most recent call last):
      File "/usr/bin/manuale", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3141, in <module>
        @_call_aside
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 640, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 941, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 828, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'manuale==1.0.2.dev0' distribution was not found and is required by the application
```

**Comment by veeti** [comment]
I think this is an issue with openSUSE's requests package: see [this bug](https://bugzilla.opensuse.org/show_bug.cgi?id=915185). You would need to wait for this to get fixed or use from a virtual environment.

It looks like you're invoking `/usr/bin/manuale`, which is a leftover from the system install you did earlier. Remove that, and it should hopefully work.
